#pragma config(Sensor, S2,     GyroScope,      sensorEV3_Gyro)
#pragma config(Sensor, S3,     UltraSonicSense, sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     ColorSense,     sensorEV3_Color)
#pragma config(Motor,  motorA,          LMotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          RMotor,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int turningPower = 50;
int straightPower = 40;
const tSensors SensorS3 = (tSensors) S3; //Ultrasonic sensor

void stopRobot() { //function to stop robot
		motor[LMotor] = 0;
		motor[RMotor] = 0;
		wait1Msec(2000);
}

void turnRight() { //function to turn the robot right
		/*motor[LMotor] = turningPower;
		motor[RMotor] = -turningPower;
		wait1Msec(475);*/

		resetGyro(S2);

		repeatUntil(getGyroDegrees(S2) > 90) {
		motor[LMotor] = turningPower;
		motor[RMotor] = -turningPower;
		}
		stopRobot();
}

/*void turnLeft() { //function to turn the robot left
		motor[LMotor] = -turningPower;
		motor[RMotor] = turningPower;
		wait1Msec(750);
}*/



void moveForward() { //function to move forward
		motor[LMotor] = straightPower;
		wait1Msec(200);
		motor[RMotor] = straightPower;
}

/*int getDistance() {
		int d = SensorValue(SensorS3); //distance from robot to wall
		return d;
}*/

task main() {
		/* 4x5 board, MUST START ON BOTTOM LEFT HAND CORNER
			 OF BOARD...i.e. whe
		*/

		float width = 21.59;
		float length = 27.94;
		float dShort = width/2; //half width
		float dLong = length/2; //half length


		//move 1
		while(SensorValue(SensorS3) > dShort) {
			moveForward();
		}
		stopRobot();
		turnRight();

		//move 2
		while(SensorValue(SensorS3) > dLong) {
			moveForward();
		}
		stopRobot();
		turnRight();


		//move 3
		while(SensorValue(SensorS3) > dShort) {
			moveForward();
		}
		stopRobot();
		turnRight();

		//move 4
		while(SensorValue(SensorS3) > dLong + length) {
			moveForward();
		}
		stopRobot();
		turnRight();

		//move 5
		while(SensorValue(SensorS3) > dShort + width) {
			moveForward();
		}
		stopRobot();
		turnRight();

		//move 6
		while(SensorValue(SensorS3) > dLong + length) {
			moveForward();
		}
		stopRobot();
		turnRight();

		//move 7
		while(SensorValue(SensorS3) > dShort + width) {
			moveForward();
		}
		stopRobot();
		turnRight();

		//move 8
		while(SensorValue(SensorS3) > dLong + 2 * length) {
			moveForward();
		}
		stopRobot();
		turnRight();



}//end main
