#pragma config(Sensor, S2,     GyroScope,      sensorEV3_Gyro)
#pragma config(Sensor, S3,     UltraSonicSense, sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     ColorSense,     sensorEV3_Color)
#pragma config(Motor,  motorB,          LMotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RMotor,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int straightPower = 50;
int deg = getGyroDegrees(S2);

//function to stop robot
void stopRobot() {
	motor[LMotor] = 0;
	motor[RMotor] = 0;
	wait1Msec(1000);
}
//function to move forward
void moveForward() {
	motor[LMotor] = straightPower;
	motor[RMotor] = straightPower;
}

task main()
{
	while (true){
	moveForward();
	resetGyro(S2);
		if (deg < 0) {
			motor[LMotor] = straightPower;
			motor[RMotor] = 0;
		}


		else if (deg > 0) {
			motor[LMotor] = 0;
			motor[RMotor] = straightPower;
		}
	}
}
